//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_1_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresler
    {
        public int AdresID { get; set; }
        public string Cadde { get; set; }
        public string Sokak { get; set; }
        public string Mahalle { get; set; }
        public int BinaNo { get; set; }
        public int Kat { get; set; }
        public string İlçe { get; set; }
        public string İl { get; set; }
        public string PostaKodu { get; set; }
    }
}
