//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_1_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emanet
    {
        public int Id { get; set; }
        public Nullable<int> KitapID { get; set; }
        public Nullable<int> ÜyeID { get; set; }
        public Nullable<int> KütüphaneID { get; set; }
        public Nullable<System.DateTime> EmanetT { get; set; }
        public Nullable<System.DateTime> TeslimT { get; set; }
    }
}
