//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_1_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitaplarKütüphane
    {
        public int ID { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<int> KitapID { get; set; }
        public Nullable<int> KütüphaneID { get; set; }
    }
}
