//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_1_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        public int KitapID { get; set; }
        public string ISBN { get; set; }
        public string KitapAd { get; set; }
        public string YayınTarihi { get; set; }
        public string SayfaSayisi { get; set; }
        public Nullable<int> YayinEviID { get; set; }
    }
}
