//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_1_0.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kütüphaneEntities3 : DbContext
    {
        public kütüphaneEntities3()
            : base("name=kütüphaneEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admin { get; set; }
        public DbSet<Adresler> Adresler { get; set; }
        public DbSet<Emanet> Emanet { get; set; }
        public DbSet<Kategoriler> Kategoriler { get; set; }
        public DbSet<KitapKategorileri> KitapKategorileri { get; set; }
        public DbSet<Kitaplar> Kitaplar { get; set; }
        public DbSet<KitaplarKütüphane> KitaplarKütüphane { get; set; }
        public DbSet<KitaplarYazarlar> KitaplarYazarlar { get; set; }
        public DbSet<Kütüphane> Kütüphane { get; set; }
        public DbSet<Uyeler> Uyeler { get; set; }
        public DbSet<Yayinevleri> Yayinevleri { get; set; }
        public DbSet<Yazarlar> Yazarlar { get; set; }
    }
}
