//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_1_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        public int UyeID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Cinsiyet { get; set; }
        public string Tel { get; set; }
        public string EPosta { get; set; }
        public Nullable<int> AdresID { get; set; }
        public string Sifre { get; set; }
        public string KullanıcıAd { get; set; }
    }
}
